### ISSUE TITLE
如何使用脚本，油猴我添加不上

### ISSUE THREAD

**Issue by c130xy** [shulandmimi/auto-answer-online-class#1]
不知道咋加在浏览器上面

**Comment by shulandmimi** [comment]
1. [下载 chrome 油猴插件](https://www.tampermonkey.net/index.php?ext=dhdg) (有则跳过)
2. [下载 油猴脚本](https://greasyfork.org/zh-CN/scripts/444829-uooc-%E4%BC%98%E8%AF%BE-%E6%99%BA%E6%85%A7%E6%A0%91-%E6%9F%A5%E9%A2%98%E5%B0%8F%E7%BB%84%E6%89%8B)

**Comment by c130xy** [comment]
学习通无法使用

**Comment by shulandmimi** [comment]
请详细给出复现方法、视频、截图、帐号（邮件发送）等复现所需要的条件

**Comment by c130xy** [comment]
![image](https://user-images.githubusercontent.com/104188963/190936057-e21b3467-469c-417e-ad8b-5aa36927afc3.png)

**Comment by c130xy** [comment]
没有任何显示

**Comment by shulandmimi** [comment]
可以把帐号借给我调试吗

**Comment by c130xy** [comment]
可以加一个联系方式吗？

**Comment by shulandmimi** [comment]
通过邮箱联系即可 `shulandmimi@163.com`
